######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

setwd("C:/Users/Carmel/Documents/@Uni/@Flinders University PhD/RWorkingDir/BUSCO")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("C:/Users/Carmel/Documents/@Uni/@Flinders University PhD/RWorkingDir/BUSCO","busco_figure-edit.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- " "

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('(LR) Unique Isoform CDS', '(LR) Unique Isoform CDS', '(LR) Unique Isoform CDS', '(LR) Unique Isoform CDS', '(SR) G4', '(SR) G4', '(SR) G4', '(SR) G4', '(SR) G7', '(SR) G7', '(SR) G7', '(SR) G7', '(SR) G2', '(SR) G2', '(SR) G2', '(SR) G2', '(SR) G3', '(SR) G3', '(SR) G3', '(SR) G3', '(SR) G6', '(SR) G6', '(SR) G6', '(SR) G6', '(SR) G5', '(SR) G5', '(SR) G5', '(SR) G5', '(LR) Clustered Reference Transcripts', '(LR) Clustered Reference Transcripts', '(LR) Clustered Reference Transcripts', '(LR) Clustered Reference Transcripts', '(LR) High Quality Iso-Seq transcripts', '(LR) High Quality Iso-Seq transcripts', '(LR) High Quality Iso-Seq transcripts', '(LR) High Quality Iso-Seq transcripts', '(SR) G8', '(SR) G8', '(SR) G8', '(SR) G8', '(SR) G1', '(SR) G1', '(SR) G1', '(SR) G1', '(SR) Combined TRINITY', '(SR) Combined TRINITY', '(SR) Combined TRINITY', '(SR) Combined TRINITY')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(39.7, 7.3, 6.1, 46.9, 48.3, 6.6, 16.1, 29.0, 49.1, 36.3, 5.5, 9.1, 56.3, 7.0, 15.2, 21.5, 46.8, 4.2, 16.5, 32.5, 46.9, 44.0, 3.1, 6.0, 47.4, 4.1, 18.7, 29.8, 44.9, 7.3, 2.9, 44.9, 35.0, 17.8, 2.9, 44.3, 50.0, 7.9, 16.0, 26.1, 57.7, 9.1, 14.1, 19.1, 54.9, 39.4, 2.1, 3.6)
my_values <- c(1331, 245, 204, 1574, 1619, 223, 540, 972, 1646, 1216, 183, 309, 1888, 236, 509, 721, 1568, 142, 553, 1091, 1574, 1475, 103, 202, 1590, 137, 627, 1000, 1506, 244, 96, 1508, 1173, 598, 97, 1486, 1676, 265, 538, 875, 1936, 306, 474, 638, 1841, 1322, 69, 122)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")

